friend_list=[]
a = input("친구을 이름을 입력하세요")
friend_list.append(a)
print(friend_list)
a = input("친구을 이름을 입력하세요")
friend_list.append(a)
print(friend_list)
a = input("친구을 이름을 입력하세요")
friend_list.append(a)
print(friend_list)
a = input("친구을 이름을 입력하세요")
friend_list.append(a)
print(friend_list)
a = input("친구을 이름을 입력하세요")
friend_list.append(a)
print(friend_list)

